### ISSUE TITLE
tsl2561 IR Daten

### ISSUE THREAD

**Issue by RenFle18** [esphome/ESPHome-Core#446] opened 2019-01-26 05:56 UTC
Hi

the tsl2561 has the possibility to output just the IR data.

If I understand the tsl2561_sensor.cpp correctly, you read out both values, but output only the result of the calculation.

at line 142, do I only have  to change 
`this->publish_state(lx);`
`this->status_clear_warning();`
to 
`this->publish_state(lx);`
`this->publish_state(data1);` (or data0)
`this->status_clear_warning();`
 to get the IR value?

Regards

**Comment by OttoWinter** [comment] 2019-01-27 15:20
Well that would partially work, though then the sensor would output both the calculation result and the IR data - probably not really useful. You can uncomment the first line though.

Closing as not a bug report

**Closed by OttoWinter** 2019-01-27 15:20 UTC
