### ISSUE TITLE
ESP32 goes to boot loops with option exrire_after

### ISSUE THREAD

**Issue by egrekov** [esphome/esphome-core#500] opened 2019-02-14 10:49 UTC
Hi!
ESP32 goes to boot loops with sensor option expire_after: 30s, without option run ok.

```yaml
esp32_ble_tracker:

sensor:
  - platform: uptime
    name: Uptime Sensor
    
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D4:5B:CE
    temperature:
      name: "Xiaomi MiJia Temperature1"
    humidity:
      name: "Xiaomi MiJia Humidity1"
    battery_level:
      name: "Xiaomi MiJia Battery Level1"
      
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D4:5B:E3
    temperature:
      name: "Xiaomi MiJia Temperature2"
    humidity:
      name: "Xiaomi MiJia Humidity2"
    battery_level:
      name: "Xiaomi MiJia Battery Level1"
```
`main.cpp`
```C
  Application::MakeVersionTextSensor application_makeversiontextsensor = App.make_version_text_sensor("Esphomelib Version");
  text_sensor::VersionTextSensor *text_sensor_versiontextsensor = application_makeversiontextsensor.sensor;
  text_sensor::MQTTTextSensor *text_sensor_mqtttextsensor = application_makeversiontextsensor.mqtt;
  ESP32BLETracker *esp32bletracker = App.make_esp32_ble_tracker();
  Application::MakeUptimeSensor application_makeuptimesensor = App.make_uptime_sensor("Uptime Sensor");
  sensor::UptimeSensor *sensor_uptimesensor = application_makeuptimesensor.uptime;
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent = application_makeuptimesensor.mqtt;
  XiaomiDevice *xiaomidevice = esp32bletracker->make_xiaomi_device({0x4C, 0x65, 0xA8, 0xD4, 0x5B, 0xCE});
  XiaomiSensor *xiaomisensor = xiaomidevice->make_temperature_sensor("Xiaomi MiJia Temperature1");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_2 = App.register_sensor(xiaomisensor);
  XiaomiSensor *xiaomisensor_2 = xiaomidevice->make_humidity_sensor("Xiaomi MiJia Humidity1");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_3 = App.register_sensor(xiaomisensor_2);
  XiaomiSensor *xiaomisensor_3 = xiaomidevice->make_battery_level_sensor("Xiaomi MiJia Battery Level1");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_4 = App.register_sensor(xiaomisensor_3);
  XiaomiDevice *xiaomidevice_2 = esp32bletracker->make_xiaomi_device({0x4C, 0x65, 0xA8, 0xD4, 0x5B, 0xE3});
  XiaomiSensor *xiaomisensor_4 = xiaomidevice_2->make_temperature_sensor("Xiaomi MiJia Temperature2");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_5 = App.register_sensor(xiaomisensor_4);
  XiaomiSensor *xiaomisensor_5 = xiaomidevice_2->make_humidity_sensor("Xiaomi MiJia Humidity2");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_6 = App.register_sensor(xiaomisensor_5);
  XiaomiSensor *xiaomisensor_6 = xiaomidevice_2->make_battery_level_sensor("Xiaomi MiJia Battery Level1");
  sensor::MQTTSensorComponent *sensor_mqttsensorcomponent_7 = App.register_sensor(xiaomisensor_6);
  sensor_mqttsensorcomponent_2->set_expire_after(30000);
```

```
[15:46:15]Rebooting...
[15:46:15]ets Jun  8 2016 00:22:57
[15:46:15]
[15:46:15]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[15:46:15]configsip: 0, SPIWP:0xee
[15:46:15]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[15:46:15]mode:DIO, clock div:2
[15:46:15]load:0x3fff0018,len:4
[15:46:15]load:0x3fff001c,len:952
[15:46:15]load:0x40078000,len:6084
[15:46:15]load:0x40080000,len:7944
[15:46:15]entry 0x40080310
[15:46:15][I][logger:071]: Log initialized
[15:46:15][C][ota:461]: There have been 9 suspected unsuccessful boot attempts.
[15:46:15]Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
[15:46:15]Core 1 register dump:
[15:46:15]PC      : 0x401dc859  PS      : 0x00060530  A0      : 0x800d1ef5  A1      : 0x3ffda850  
[15:46:15]A2      : 0x00000000  A3      : 0x00007530  A4      : 0x00000000  A5      : 0x3ffd5974  
[15:46:15]A6      : 0x3ffd6cf4  A7      : 0x00000000  A8      : 0x00000001  A9      : 0x3ffda810  
[15:46:15]A10     : 0x3fb7f702  A11     : 0x3fb7f702  A12     : 0x3ffc8dbc  A13     : 0x0000ff00  
[15:46:15]A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001d  
[15:46:15]EXCVADDR: 0x0000005c  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
[15:46:15]
[15:46:15]Backtrace: 0x401dc859:0x3ffda850 0x400d1ef2:0x3ffda870 0x401af24a:0x3ffdaa40
[15:46:15]
[15:46:15]Rebooting...
[15:46:15]ets Jun  8 2016 00:22:57
[15:46:15]
[15:46:15]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[15:46:15]configsip: 0, SPIWP:0xee
[15:46:15]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[15:46:15]mode:DIO, clock div:2
[15:46:15]load:0x3fff0018,len:4
[15:46:15]load:0x3fff001c,len:952
[15:46:15]load:0x40078000,len:6084
[15:46:15]load:0x40080000,len:7944
[15:46:15]entry 0x40080310
[15:46:16][I][logger:071]: Log initialized
[15:46:16][C][ota:461]: There have been 10 suspected unsuccessful boot attempts.
[15:46:16][E][ota:466]: Boot loop detected. Proceeding to safe mode.
[15:46:16][C][wifi:029]: Setting up WiFi...
[15:46:16][D][wifi:260]: Starting scan...
[15:46:18][D][wifi:275]: Found networks:
...
[15:46:20][C][ota:129]: Over-The-Air Updates:
[15:46:20][C][ota:130]:   Address: 192.168.10.118:3232
[15:46:20][C][ota:132]:   Using Password.
[15:46:20][W][ota:136]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
[15:46:20][I][ota:477]: Waiting for OTA attempt.
```

**Comment by OttoWinter** [comment] 2019-02-14 16:01
https://github.com/esphome/esphome-core/issues/499

Also duplicate of https://github.com/esphome/esphome-core/issues/372#issuecomment-454392413

**Closed by OttoWinter** 2019-02-14 16:01 UTC
